# Generated by Django 6.0 on 2026-01-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def insert_initial_data(apps, schema_editor):
    Tag = apps.get_model('api', 'Tag')
    tags = [
        'World',
        'Politics',
        'Economy',
        'Technology',
        'Health',
        'Science',
        'Environment'
    ]
    for tag in tags:
        Tag.objects.get_or_create(name=tag)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='api.tag'),
        ),
        migrations.CreateModel(
            name='TagsAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redactor', models.ForeignKey(limit_choices_to={'user_type': 'Redactor'},
                                               on_delete=django.db.models.deletion.CASCADE,
                                               related_name='assigned_tags', to=settings.AUTH_USER_MODEL)),
                ('tag',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_redactors',
                                   to='api.tag')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('redactor', 'tag'), name='unique_redactor_tag_assignment')],
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]