# Generated by Django 6.0 on 2026-01-28 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagsAssignment',
            new_name='RedactorTagAssignment',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
        migrations.CreateModel(
            name='EntryTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tags', to='api.entry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_entries', to='api.tag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'tag'), name='unique_entry_tag_assignment')],
            },
        ),
    ]
