# Generated by Django 6.0 on 2026-04-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_entry_sources_request_requesttagassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="sources",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="request",
            name="articles",
            field=models.JSONField(),
        ),
    ]
